#!/usr/bin/env node

/**
 * Script to prepare environment variables for Netlify build
 * This ensures VITE_* variables are available during build time
 */

const fs = require('fs');
const path = require('path');

const frontendEnvPath = path.join(__dirname, '..', 'frontend', '.env.production');

// Get environment variables from process.env
const supabaseUrl = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
const supabaseKey = process.env.VITE_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.warn('⚠️  Warning: Supabase environment variables not found');
  console.warn('   Make sure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are set in Netlify');
  console.warn('   or in your local .env.local file');
  
  // Don't fail the build, just warn
  process.exit(0);
}

// Create .env.production file for Vite
const envContent = `# Auto-generated by prepare-env.js
# This file is created during build time
VITE_SUPABASE_URL=${supabaseUrl}
VITE_SUPABASE_ANON_KEY=${supabaseKey}
`;

try {
  fs.writeFileSync(frontendEnvPath, envContent, 'utf8');
  console.log('✅ Environment variables prepared successfully');
  console.log(`   Created: ${frontendEnvPath}`);
} catch (error) {
  console.error('❌ Failed to create .env.production:', error);
  process.exit(1);
}

